import Head from 'next/head'
import { useState } from 'react';
// import Image from 'next/image'
import { Header, Hero, Skills, Projects } from '../components/organisms'

export default function Home() {
  const [language, setLanguage] = useState('english');

  return (
    <div className="bg-white text-dark h-screen overflow-y-scroll overflow-x-hidden z-0 scroll-smooth scrollbar-thumb-[#40474e] scrollbar-thin">
      <Head>
        <title>Conosciuto Ivan</title>
        <meta name="descrisption" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://api.fontshare.com/v2/css?f[]=red-hat-display@900,300,700,400,800,200&display=swap" rel="stylesheet" />
      </Head>
      <Header language={language} setLanguage={setLanguage}/>
      <section id="hero" className="">
        <Hero language={language}/>
      </section>
      <section id="skills" className="">
        <Skills language={language}/>
      </section>
      <section id="projects" className="h-full">
        <Projects language={language}/>
      </section>
    </div>
  )
}
